### ISSUE TITLE
Mention List overflow windows when cursor is at the edge & one parent in the DOM has position: relative

### ISSUE THREAD

**Issue by Tonio-lavanda** [dmacfarlane/angular-mentions#102]
Hello,

First thanks for this library, very useful and it works great.

I have the exact same issue than described in this [bug report](https://stackblitz.com/edit/angular-xvqj8k?file=src/app/app.component.ts)

The problem is that when you type '@' too close to the right edge of the screen, the mention list doesn't appear.

I reproduced on this [stackblitz](https://stackblitz.com/edit/angular-xvqj8k?file=src%2Fapp%2Fapp.component.css)

I think the problem comes from the fact that somewhere in the DOM, a parent component has `position: relative` and the method `checkBounds` within `mention-list.component.ts` doesn't understand that correctly (just a hint, you know better than me):
```
    if (bounds.left+bounds.width>window.innerWidth) {
      left = (window.innerWidth - bounds.width - 10);
    }
``` 

I could not find a workaround for this as this component is used in my case in a big application and I need these `position: relative` for some layout purpose in some higher components.

**Comment by dmacfarlane** [comment]
You are right, the fix for #95 isn't working when `position: relative` is used in your example. I'm not sure on the fix, but I'd guess bounds calculation needs some work.

**Comment by shyamal890** [comment]
@dmacfarlane can you utilize `ng-bootstrap` as a dependency as dropdown code handles all these issues.

**Comment by thiagops** [comment]
I'm having this issue as well

**Comment by nettz** [comment]
I am having the same issue as well.

**Comment by dmacfarlane** [comment]
Could someone check if this is fixed in the latest version?

**Comment by tanmayrajani** [comment]
seems to be working in the same aforementioned stackblitz by updating to 1.1.3

**Comment by AsifKhurshid101** [comment]
I have used mention list in textarea.. I have fix this issue like this
opened(update?) {
        const Parentbox_id = update ? 'Comment_Parent_' + update : 'text_area_parent';

        setTimeout(() => {
            var list = document.getElementById(Parentbox_id).querySelector(`mention-list[class="dropup"]`) as HTMLElement;

            if (!list) {
                list = document.getElementById(Parentbox_id).querySelector(`mention-list[class="null"]`);
            }

            let selObj = this.getWindowSelection(undefined);
            var selRange = selObj.getRangeAt(0);
            var anchorNode = selObj.anchorNode;
            var parentNode = anchorNode.parentNode !== null ? anchorNode.parentNode : selRange.commonAncestorContainer.parentNode;

            var offsetHeight = parentNode.offsetHeight; //19 fpr <p> tag
            var offsetTop = parentNode.offsetTop; //distance from top

            var top = update ? 27 : 31;

            if (parentNode.previousElementSibling) {
                top = offsetTop + (update ? 15 : 17);
                top = update ? top : top > 56 ? 56 : top;
            }

            if (list){
                //console.log("margin left", list.style.left);
                var getMarginLeft = list.style.left;
                var getActualValue = getMarginLeft.replace("px", "");
                var checkIfEdgeOut = Number(getActualValue);
                if(checkIfEdgeOut > 0)
                {
                    list.style.cssText = `display:block !important;z-index:9999999999; position:absolute; left:${list.style.left}; top:${top}px`;
                }
                else {
                    var str = "9.5px";
                    list.style.cssText = `display:block !important; position:absolute; left:${str}; top:${top}px`;
                    setTimeout(() => { list.style.cssText = `z-index:9999999999;`; }, 3000);
                }
            }

        }, 0);
    }
