### ISSUE TITLE
mentionSelect event

### ISSUE THREAD

**Issue by roohbakhshmasoud** [dmacfarlane/angular-mentions#103]
i want to import selection into an array but when i use : 

 **this.selectionItem.push(selection)** 

 i'm facing with this error:

**Cannot read property 'push' of undefined**

now i don't know what to do ?!
please help me.
thanks

**Comment by dmacfarlane** [comment]
Try adding bind to the function, for example:
```
[mentionConfig]="{items:items, mentionSelect:format.bind(this)}"
```
