### ISSUE TITLE
Support mentions that contain spaces

### ISSUE THREAD

**Issue by komxvl** [dmacfarlane/angular-mentions#106]
When we have terms which consist of two words, this item doesn't show on the list, when typing space.
It'd be great if the user typing backspace and list will be shown again when you have two words.
Thnx.
https://stackblitz.com/edit/angular-mentions-7uknh2

**Comment by pgedzba** [comment]
I have added an option to allow space in mentions in this pull request: https://github.com/dmacfarlane/angular-mentions/pull/115

**Comment by komxvl** [comment]
@dmacfarlane could you please update your fantastic library with @pgedzba changes, thnx guys!

**Comment by dmacfarlane** [comment]
This is now available in version 1.1.0.

**Comment by komxvl** [comment]
Great, thnx!
