### ISSUE TITLE
Feature Request: A flag which is set till the time dropdown list is open

### ISSUE THREAD

**Issue by shyamal890** [dmacfarlane/angular-mentions#109]
Sometimes lets say you are taking an action when a user presses enter button on the input. With this library you are still using the Enter button to select the dropdown option but at he same time the underlying action on the input is also trigger. 

To avoid this, need a flag to be set when the dropdown is open.

**Comment by shyamal890** [comment]
@dmacfarlane Hi can you please update if this is something that can be worked out?

**Comment by dmacfarlane** [comment]
The mention directive has a variable called `searching` that is set when the dropdown is open. Is that what you are looking for?

**Comment by shyamal890** [comment]
Yes that would be great if exposed

**Comment by shyamal890** [comment]
@dmacfarlane any chance you can expose this variable?

**Comment by pgedzba** [comment]
i have added isOpen flag in this pull request: https://github.com/dmacfarlane/angular-mentions/pull/115

**Comment by dmacfarlane** [comment]
My suggestion for this is to add `@Output() opened:EventEmitter<void>` and `@Output closed:EventEmitter<void>` to match the material design spec for autocomplete.
