### ISSUE TITLE
Searching and filtering is not working with Embedded Editor

### ISSUE THREAD

**Issue by callratnesh** [dmacfarlane/angular-mentions#110]
Hi, thanks for this great module. 
Please help me resolve an issue which is related with search in **Embedded Editor**.
Issue can be reproduces in demo app link [http://dmacfarlane.github.io/angular-mentions/].
in embedded editor, when press shift+@ key the list appears. When you start type the list is getting filtered . However if you hit enter key to reach new line and try to search with more than one chars the search result is not correct. also list is getting disappeared.

PS. this issue is happening when you hit enter key for a new line and then search .

Looking for your response.
Many thanks
Ratnesh

**Comment by VijiVgsN** [comment]
Hi, We are struggling with the same issue. Can you please give as the quick fix or at least give some solution?

**Comment by janardhanbobba522** [comment]
The same issue we are facing. If anyone found any workaround please post

**Comment by vijayalakshmin1203** [comment]
Hi, This issue has been fixed and I have requested the PR for this fix.

https://github.com/dmacfarlane/angular-mentions/pull/113

**Comment by dmacfarlane** [comment]
Fixed in version 1.0.4. Thanks @vijayalakshmin1203 for the fix.
