### ISSUE TITLE
Feature Request: show mention-item with image

### ISSUE THREAD

**Issue by krishnasaikumarraju** [dmacfarlane/angular-mentions#111]
Requesting feature:
please refer below image at comment section which is populating mentions functionality with an image.
![image](https://user-images.githubusercontent.com/42143138/62548070-dda02f80-b883-11e9-997c-5df54c34122c.png)

please could you suggest me that how to get that feature.

**Comment by dmacfarlane** [comment]
Here's an example: https://stackblitz.com/edit/angular-mentions-avatar

**Comment by krishnasaikumarraju** [comment]
Could you please suggest me on how to use multiple triggerChar:'#' on a single input tag.

**Comment by dmacfarlane** [comment]
Closing as this is already supported.
