### ISSUE TITLE
Click on mention item, show mention list items.

### ISSUE THREAD

**Issue by komxvl** [dmacfarlane/angular-mentions#116]
How I can to show mention list when click on @items. [Like this](https://jsfiddle.net/ourcodeworld/83vLzhw2/3/?utm_source=website&utm_medium=embed&utm_campaign=83vLzhw2)

**Comment by pgedzba** [comment]
You want to open mention list after clicking a button?

**Comment by komxvl** [comment]
No, on click mention item in input, @Peter, click on Peter show list.

**Comment by Alec-Aldrine-Lakra** [comment]
@komxvl on selecting an input create a span element inside which you place the selected element. To that span element add an event listener and within the event function generate a keyboard event somewhat like this 

```
   const event = new KeyboardEvent("keydown", { key : `@`, code : `Digit2`});
```

**Comment by komxvl** [comment]
Hi @Alec-Aldrine-Lakra . Thnx for your answer, if you have some similar functionality, could you share, please. In this [library](https://github.com/afry/quill-mention/pull/115), @rajshivam did it.
