### ISSUE TITLE
DropUp is not working with multiple triggerChars

### ISSUE THREAD

**Issue by pgedzba** [dmacfarlane/angular-mentions#125]
As in the topic, dropUp is not working with multiple triggerChars. Here is my mention config:
`public mentionConfig = {
    mentions: [
      {
        items: ['Jan', 'Adam', 'Basia', 'Barbara'],
        triggerChar: '#'
      },
      {
        items: ['Jan', 'Adam', 'Basia', 'Barbara'],
        triggerChar: '@'
      }
    ],
    dropUp: true
  };`
Putting dropUp inside mentions didn't change anything. Any idea how to fix this? I can try do it on my own, but do you have any preferences @dmacfarlane ?

**Comment by dmacfarlane** [comment]
It looks like that got broken when we removed bootstrap. If you include the bootstrap css and add `disableStyle:true` to mentionConfig then it works. It would be great if you can identify the styles required for dropUp to work.
