### ISSUE TITLE
Styling the Mentions

### ISSUE THREAD

**Issue by Alec-Aldrine-Lakra** [dmacfarlane/angular-mentions#132]
mentionSelect() can just format text before being displayed, I want to add CSS styles to my selected item as it is displayed on the screen . How can I achieve that ?

**Comment by thearchitgarg** [comment]
@Alec-Aldrine-Lakra Do you want to add styles in the text area text which renders after you click an item from mentions list?

**Comment by telshahawy** [comment]
did you find the answer? I am trying to give it a simple style but with no luck.

**Comment by Alec-Aldrine-Lakra** [comment]
There's no point in styling by altering the angular-mentions, instead I performed styling after receiving the input selected by the user
