### ISSUE TITLE
selected value output

### ISSUE THREAD

**Issue by borriej** [dmacfarlane/angular-mentions#135]
Hi,

Im using this with Angular 8, bootstrap 4.

added this scss to make the hide / show working :
```
// angular-metions
mention-list {
  ul.dropdown-menu {
    visibility: visible !important;
    opacity: 1 !important;
  }
}
```

now i have another problem, how do I get the value?
I want an output function which emits the object i have selected.

Currently this is not possible? Or am i reading the docs wrong?

Tried 
```
       (searchTerm)="onMentionSelect($event)"
       (closed)="onMentionSelect($event)"
```

Goal:
> pass array of user objects
> show the names
> on enter / click  > emit the User object

at the moment im only getting the first letter typed

Edit: it seems like the it is an issue with the template output?

when I use mentionConfig
```
    this.mentionConfig = { mentionSelect: this.onMentionSelect };

  onMentionSelect(e: any): void {
    console.log(e);
    console.log(this.mentionSelected);
    // this.mentionSelected.emit('test');
    return e.label;
  }
```
it does return the object, but another issue there is that it cannot access the class scope, so i cannot use event emitter to emit the value to another component

**Comment by akhil5** [comment]
I used localStorage to get the id array after trying lots of things.

onMentionSelect(e: any): string {
		
		let userIds = JSON.parse(localStorage.getItem('userIds'));
		
		if( userIds ) {
			userIds.push(e.id);
		} else {
			userIds = [e.id];
		}
		localStorage.removeItem('userIds');
		localStorage.setItem('userIds', JSON.stringify( userIds ));
		return e.label;
	}

**Comment by dmacfarlane** [comment]
See #156. The `(itemSelected)` output event was added in the 1.2.0 release.

**Comment by dmacfarlane** [comment]
Closing old issue.
