### ISSUE TITLE
when enableIvy MentionsModule couldn't be resolved as module,directive,component,pipe

### ISSUE THREAD

**Issue by abdallahshaaban0** [dmacfarlane/angular-mentions#138]
I'm trying to working with ivy for angular 9 project but i faced this issues which stopped me 
MentionsModule couldn't be resolved as module,directive,component,pipe
 
Angular-project

**Comment by aeslinger0** [comment]
I just upgraded to Angular 9 and did not experience this. @abdallahshaaban0 can you include any more details that might help track down the problem.

**Comment by adnanelamghari** [comment]
try adding this to your tsConfig  : ````"skipLibCheck": true,````

{
   .
   .
   .
  "compilerOptions": {
       .
       .
       "skipLibCheck": true,
       .
       .
  },
}

**Comment by drewswanner** [comment]
I would be interested in looking into this.

**Comment by dmacfarlane** [comment]
@drewswanner the first thing to do would be to try and reproduce this issue. It was reported a while ago an may not be an issue anymore.

**Comment by dmacfarlane** [comment]
Closing old issue.
