### ISSUE TITLE
List options not showing value 

### ISSUE THREAD

**Issue by ivandres** [dmacfarlane/angular-mentions#139]
Hi,

I was using this plugin in Angular 7 and it was working fine. Now I updated to Angular 9 and now the list options are not showing the value.

I am using an object and labelKey

`<textarea formControlName="test"
            [mention]="users"
            [mentionConfig]="{ triggerChar: '@', maxItems: 3, labelKey: 'FullName', mentionSelect: onMentionSelect }"></textarea>`

I tried to do the same with an array of string as the example and I got the same result.

Here is a screenshot of how it looks like:

https://share.getcloudapp.com/7KuRbKyd

**Comment by CheckMater** [comment]
I was also having the same problem as you using a simple array of strings and I solved it doing this:

Angular 9.0.5
angular-mentions 1.1.3

```
<input [mention]="members" [mentionListTemplate]="newItemTemplate" type="text">

<ng-template #newItemTemplate let-item="item">
  {{item['label']}}
</ng-template>
```

**Comment by ivandres** [comment]
Thank you @CheckMater this worked right away!
