### ISSUE TITLE
Can't access a trigger char in mentionSelect event

### ISSUE THREAD

**Issue by dbuitrago** [dmacfarlane/angular-mentions#143]
Hello!

It would be nice to get triggerChar which mentionSelect event was triggered with since for different triggerChars we can use different handlers to format the return.

**Comment by dmacfarlane** [comment]
Similar to #97.

**Comment by dbuitrago** [comment]
The event is different when the user select a item into the mention list. the "mentionSelect" event not specify the trigger char that open the list so when there are two trigerchar configuration and emit the event, You don't know wich trigger char wasw selected
Thanks

**Comment by dmacfarlane** [comment]
Fixed in the 1.2.0 release.
