### ISSUE TITLE
Display 'mention list' menu position not change from initial position when scrolling

### ISSUE THREAD

**Issue by safaeLaji** [dmacfarlane/angular-mentions#148]
Position of mention list  menu does not change from initial position when the outermost div parent of the element mention contains scroll, if the element of mention is in the bottom of the div, we could not see the menu if it is displayed, we have to scroll the content, but the position of the menu is still far in the bottom with a fixed position.
![screenshot](https://user-images.githubusercontent.com/35955421/78128006-168da580-740d-11ea-9d94-e308fb3321c4.png)

**Comment by dmacfarlane** [comment]
Can you provide a stackblitz?

https://stackblitz.com/edit/angular-mentions

**Comment by safaeLaji** [comment]
Yes, see example below:
https://stackblitz.com/edit/angular-mentions-crk6uv

**Comment by dmacfarlane** [comment]
Thanks, if you add `position:relative` to the `div` it will open the list in the correct position inside the div, but it will be out of view due to the div scroll bar.

**Comment by safaeLaji** [comment]
Thanks, it works nicely
