### ISSUE TITLE
Allow option to choose between startWith and includes

### ISSUE THREAD

**Issue by jpsmedeiros** [dmacfarlane/angular-mentions#154]
Hello, I would like to request the option to choose between the startWith and the includes function when filtering the data. 

OBS: There is already a pull request that changes the startWith to the includes that would also solve my issue.

**Comment by TomJahncke** [comment]
I also would love to mentions to be includes rather than startWith.  I do appreciate the desire to make this a configurable option.    Is there is a rough ETA?

**Comment by kalianne-ciandt** [comment]
I solved this with a workaround:

```
        <input
          ...
          [mention]="filteredTeamMembers"
          [mentionConfig]="{ triggerChar: '@', maxItems: 5, labelKey: 'displayName', disableSearch: true }"
          (searchTerm)="onSearch($event)"
          (itemSelected)="onMention($event)"
        />

  onSearch(event): void {
    this.filteredTeamMembers = this.allTeamMembers.filter(member => member.displayName.toLowerCase().includes(event.toLowerCase()));
  }

  onMention(itemSelected: MicrosoftTeamMember): void {
    this.mentionedUsers.push(itemSelected);
    this.filteredTeamMembers = this.allTeamMembers;
  }

```

**Comment by kalianne-ciandt** [comment]
We solved this with a workaround:

```
<input
 ...
 [mention]="filteredTeamMembers"
 [mentionConfig]="{ triggerChar: '@', maxItems: 5, labelKey: 'displayName', disableSearch: true }"
 (searchTerm)="onSearch($event)"
 (itemSelected)="onMention($event)"
/>

onSearch(event): void {
 this.filteredTeamMembers = this.allTeamMembers.filter(member => member.displayName.toLowerCase().includes(event.toLowerCase()));
}

onMention(itemSelected: ...): void {
 this.mentionedUsers.push(itemSelected);
 this.filteredTeamMembers = this.allTeamMembers;
}
```

**Comment by dmacfarlane** [comment]
The 1.3.0 release adds a `mentionFilter` option that can be used to customize the filtering implementation.

**Comment by TomJahncke** [comment]
@dmacfarlane thank you so much.  Do you happen to have a working example or a code snippet demoing how to use the `mentionFilter`?

**Comment by dmacfarlane** [comment]
@TomJahncke there is an example in the demo app: demo-config.component.ts.

**Comment by TomJahncke** [comment]
@dmacfarlane thanks!  I got it to work, really appreciated this feature change and the overall project!
