### ISSUE TITLE
Add event emitter to emit selected item from list

### ISSUE THREAD

**Issue by sobhardwaj** [dmacfarlane/angular-mentions#156]
<input
   [mention]="items" class="form-control" 
   contenteditable="true" 
(selecteditems)="selected($event)"
(multiselect)= "true"
   style="border:1px lightgrey solid;min-height:88px" 
   [mentionConfig]="{triggerChar:'@',labelKey:'id'}"
> 
</div>

**Comment by dmacfarlane** [comment]
Linking to PR #112

**Comment by dmacfarlane** [comment]
Fixed in the 1.2.0 release.
