### ISSUE TITLE
Ability to pass different key for items search/filtering from the list

### ISSUE THREAD

**Issue by ease** [dmacfarlane/angular-mentions#163]
Would be good if we could pass an information to the config, so that search over the items is performed by some custom property, and not always by labelKey we provide, as found [here](https://github.com/dmacfarlane/angular-mentions/blob/5f5dccde9634bbec43a4e49e63ad8813f31fec9e/projects/angular-mentions/src/lib/mention.directive.ts#L329).
```.ts
objects = objects.filter(e => e[this.activeConfig.labelKey].toLowerCase().startsWith(searchStringLowerCase));
```

Would be good to be able to do the following:
```.ts
      this.mentionConfig = {
        mentions: [
          {
            items: this.tagList,
            triggerChar: '@',
            labelKey: 'name'
          },
          {
            items: this.emojiList,
            triggerChar: ':',
            labelKey: 'name',
            searchKey: 'myCustomId', <--
            mentionSelect: (emoji) => this.formatSelectedEmoji(emoji),
            maxItems: 5
          },
        ]
      }
```

Because of the following situations (because `startsWith` doesn't work good with :#@ some special sign because user never searches for `:`):
![angular-mentions search](https://user-images.githubusercontent.com/9357793/87800450-b2251380-c84e-11ea-9a5d-af163fd28e2d.png)

Awesome library guys.

**Comment by dmacfarlane** [comment]
The 1.3.0 release adds a `mentionFilter` option that can be used to customize the filtering implementation.
