### ISSUE TITLE
Disappearing scroll (IE 11)

### ISSUE THREAD

**Issue by habtamudegifie** [dmacfarlane/angular-mentions#172]
Hi there, your  module has been used for our angular application. As you could see on attached image, when you click on scroll bar the dropdown item disappears from the screen. For more information you can check  [Click here for a Demo](http://dmacfarlane.github.io/angular-mentions/). N.B this only for Internet explorer and it ok with other browsers.
Thanks
![image](https://user-images.githubusercontent.com/72499736/95323432-d10fd080-08a6-11eb-9111-64e05a2f6e97.png)

**Comment by dmacfarlane** [comment]
IE11 is end of life so this is unlikely be be fixed.
