### ISSUE TITLE
Not working for chrome 86

### ISSUE THREAD

**Issue by chaouiy** [dmacfarlane/angular-mentions#174]
After updaging my chrome browser to `version 86.0.4240.75 (Official Build) (64-bit)` plugin is not working. Nothing happens when I type `@`

**Comment by dmacfarlane** [comment]
It's working for me. Is the [demo page](http://dmacfarlane.github.io/angular-mentions/) working?

**Comment by chaouiy** [comment]
Even the demo page is not working.

**Comment by kalianne-ciandt** [comment]
Here it is working perfect! Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by chaouiy** [comment]
I have Ubuntu 20 in case it matters.

**Comment by kalianne-ciandt** [comment]
> I have Ubuntu 20 in case it matters.

Here is Ubuntu 18.04

**Comment by dmacfarlane** [comment]
The latest version seems to be working fine.
