### ISSUE TITLE
Add usage of mentionListTemplates to docs

### ISSUE THREAD

**Issue by MSkico** [dmacfarlane/angular-mentions#176]
Hi! 

thanks for the nice library! It works very well. I needed custom item templates in the dropdown and discovered (while researching if I could implement it into the lib myself) that it is all there already! I think this information and a short usage guide would benefit a lot of people!

Here's an addition to the docs for your convenience:

# Custom item templates

Mention list items can be customized by binding a template to the `mentionListTemplate` property. 

![image (1)](https://user-images.githubusercontent.com/74422374/100726089-cb28fe00-33c4-11eb-883d-4decbd2fb35e.jpg)

In the following example, the `mentionItems` array contains complex objects with a `Label` and an `Image` property. 

```

<!-- Example --->

<input class="form-control" type="text" [mention]="mentionItems" [mentionConfig]="mentionConfig" [mentionListTemplate]="mentionListTemplate">

<!-- .... --->

<ng-template let-item="item" #mentionListTemplate>
    <div class="row">
        <div class="col-3">
            <div class="avatar avatar-xs">
                <img [src]="item.Image" alt="{{item.Label}}" class="avatar-img rounded-circle">
            </div>
        </div>
        <div class="col-9">
            {{item.Label}}
        </div>
    </div>
</ng-template>

```

For the insertion to work properly with complex objects, define `MentionConfig`s `mentionSelect` property. For example, if your item objects contain a string property `InsertionValue`, set the config as

```
mentionConfig = {
    // ...   
    mentionSelect: (item : any) => {
      return item.InsertionValue;
    }
}
```

**Comment by MSkico** [comment]
![Uploading image (1).jpg…]()

**Comment by dmacfarlane** [comment]
Thanks for this suggestion. I've updated the docs with link to an example.
