### ISSUE TITLE
Can we search by last name?

### ISSUE THREAD

**Issue by fzs1994** [dmacfarlane/angular-mentions#179]
Currently, I am able to search by full name by enabling space, but is there a way we can search by last name only?
![image](https://user-images.githubusercontent.com/10684213/103074187-1ebaf000-45ef-11eb-8ad7-9d470e0b468a.png)

**Comment by dmacfarlane** [comment]
You will be able to do that with the `mentionFilter` option that is in the next release.

**Comment by fzs1994** [comment]
In case if anyone is looking for this:

![image](https://user-images.githubusercontent.com/10684213/166889707-026e18ef-b905-447a-a554-6fd4039ee28e.png)
