### ISSUE TITLE
Demo app not working

### ISSUE THREAD

**Issue by bkmalan** [dmacfarlane/angular-mentions#182]
Hey,

I wanted to implement angular-mentions in tiny editor.

I'm not able to get it working with the docs,I tried to run the demo app that didn't either.

Please help me integrate mentions with TinyMCE editor.

Thank you in advance.

**Comment by konstantinosftw** [comment]
Hey @bkmalan, you can check out this [stackblitz](https://stackblitz.com/edit/angular-mentions-avatar?file=app%2Fapp.component.ts) to get an idea. The specific one implements a custom template that also shows the avatar of each user, but you can easily remove it by simply deleting the `mentionListTemplate`.

**Comment by bkmalan** [comment]
Hey @konstantinosftw ,
Thanks for reaching out.
I'm trying to use the same editor that is being displayed in the demo page.

Just that I'm not sure how to get it implemented, so I tried to run the demo app on my local but couldn't get it up and running.

If you have inputs on this kindly help me out.

Thanks,
