### ISSUE TITLE
Mouse selection is not working when used in @kolkov/angular-editor.

### ISSUE THREAD

**Issue by akshaysalekar108** [dmacfarlane/angular-mentions#185]
Hi ,
I wanted to use this library with kolkov angular editor but selection with mouse click is not working only keyboard selection works.
Any solution or work around for this. 
Thank you

**Comment by akshaysalekar108** [comment]
commented nativeElement.focus(); from mentioned.directive.ts and It worked.

**Comment by Prashant10** [comment]
I tried the same thing, but no luck. Can you please help? I am using the same control rich text editor with angular mention.

**Comment by kimlambiguitoppolis** [comment]
still getting this as well

**Comment by aagache** [comment]
Issue still occurs. Why is this issue closed?

**Comment by dmacfarlane** [comment]
See https://github.com/dmacfarlane/angular-mentions/issues/248#issuecomment-1998933362 for a potential fix to this problem.
