### ISSUE TITLE
Enter key is not moving the cursor to next line when a mention typed which is not in available list

### ISSUE THREAD

**Issue by man0jR** [dmacfarlane/angular-mentions#186]
When entering a mention which is not available in the items list, then pressing enter key to reach the next line is not working inside textarea.
This issue is replicable in the demo given in the github page as well.

Ex: triggerChar is @
items is ["Alex","Ant","Apple"]

then typing @asd then pressing enter key(without space) is not navigating to next line of textarea.
It should either show no matches or it should allow to navigate to the next line.

**Comment by dmacfarlane** [comment]
Fixed in the 1.4.0 release.
