### ISSUE TITLE
Cannot use MentionModule twice in the same app - different components

### ISSUE THREAD

**Issue by CreativeZoller** [dmacfarlane/angular-mentions#189]
Hey guys!

I was using this package for a long time already. Now that I want to use in another additional component, I tried to use it the same way as before.
Getting a lot of options back from an API, populate them into an empty variable. And in the template, I add the proper `[mention]="customerMessageItems"` parts to use the package functionality in action. It is fine in the place I started to use in the first place, but now where I want to use it the second time, it is just not working. Also the variable for all the mention items are the same in both places.
I am using the followings (for Angular, updating version is not an option, we are having a lot of legacy-kind of codes which require lesser versions :/
```Angular CLI: 10.2.3
Node: 14.15.4
OS: darwin x64

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            10.2.3
@angular-devkit/schematics      10.2.3
@angular/cdk                    10.2.7
@angular/cli                    10.2.3
@angular/material               10.2.7
@schematics/angular             10.2.3
@schematics/update              0.1002.3
rxjs                            6.6.7
typescript                      4.0.8
```
And now only for the second place where I want to apply it, it says me the following error message and no matter what I cannot figure out the source of this problem:
```
Error: src/app/components/shared/message-form/message-form.component.html:15:9 - error NG8002: Can't bind to 'mention' since it isn't a known property of 'textarea'.
```

**Comment by dmacfarlane** [comment]
Normally you will see that error if you haven't imported the module:

https://angular.io/guide/ngmodule-faq#what-does-cant-bind-to-x-since-it-isnt-a-known-property-of-y-mean

Check that you have imported the MentionsModule into the module containing your additional component.

**Comment by CreativeZoller** [comment]
I have. As I already mentioned, I am already using it on another component in the same project/app.

**Comment by dmacfarlane** [comment]
It needs to be imported into each module where it is used. The error indicates that wasn't done.
