### ISSUE TITLE
Plugin not working on chrome !

### ISSUE THREAD

**Issue by KessoumML** [dmacfarlane/angular-mentions#195]
I'm using this plugin for a while but suddenly it stopped working on chrome.
I didn't investigate the details to provide more information.
The demo also not working on chrome Version 94.0.4606.81 (Official Build) (64-bit) / Ubuntu 20.04

[http://dmacfarlane.github.io/angular-mentions/](http://dmacfarlane.github.io/angular-mentions/)

Does anyone encountered this issue?

**Comment by dmacfarlane** [comment]
Is this still an issue? If so can anyone provide any more details?
