### ISSUE TITLE
space in search not working 

### ISSUE THREAD

**Issue by tahirjamil92** [dmacfarlane/angular-mentions#200]
I am using angular 8 and 1.1.2 version of angular mentions in my project and search is not working 
i fork the repo of angular-mentions and try the latest version but still its not working for me even in updated versions 
Please share your comments on this issue.

https://stackblitz.com/edit/angular-mentions-awdzvb?file=app/app.component.html

**Comment by dmacfarlane** [comment]
You need to place the configuration options in a `mentionConfig` directive, for example:

```html
<input type="text" [mention]="items" [mentionConfig]="{allowSpace:true}" />
```
