### ISSUE TITLE
Angular 11 Error: ./node_modules/angular-mentions/fesm2015/angular-mentions.mjs 1075:12-24 Can't import the named export 'CommonModule' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by Usama-GITStack** [dmacfarlane/angular-mentions#228]
Hi @dmacfarlane  I have updated angular 9 to 11 and it causes me this error please help me
Error: ./node_modules/angular-mentions/fesm2015/angular-mentions.mjs 1075:12-24
Can't import the named export 'CommonModule' from non EcmaScript module (only default export is available)

**Comment by dmacfarlane** [comment]
Which version of angular-mentions are you using?
