### ISSUE TITLE
How can we highlight or bold selected(Mention) words

### ISSUE THREAD

**Issue by moon-web75** [dmacfarlane/angular-mentions#235]
If I have selected @abc then how to highlight ABC

**Comment by moon-web75** [comment]
If I have selected @ABC then how to highlight ABC

**Comment by dmacfarlane** [comment]
See #132, #98, https://github.com/dmacfarlane/angular-mentions/issues/58, https://github.com/dmacfarlane/angular-mentions/issues/57, https://github.com/dmacfarlane/angular-mentions/issues/34, https://github.com/dmacfarlane/angular-mentions/issues/15.
