### ISSUE TITLE
We need to remove mention user list event.

### ISSUE THREAD

**Issue by moon-web75** [dmacfarlane/angular-mentions#245]
For example,

We have specified A but we need to specify A1 then we have to remove A from the selected user list then how can I remove A, so please add remove mentioned event

**Comment by bytrangle** [comment]
Can't you backspace-delete A in the input field, type the trigger character again and choose A1?

**Comment by bytrangle** [comment]
Surprised to see an issue being closed by the owner, because I didn't think that this project is still maintained.
