### ISSUE TITLE
multiple Autocomplete for multiple tag

### ISSUE THREAD

**Issue by v2neeta** [dmacfarlane/angular-mentions#25]
Is there any feature for multiple tag in same textbox in anugular 2.

**Comment by dmacfarlane** [comment]
Yes, you can use multiple mentions in a textbox. Try it out on the demo page.

**Comment by neeta90** [comment]
like @ and # if i want to use. In current only @ is used.

**Comment by dmacfarlane** [comment]
Duplicate of #22

**Comment by yasir-rafiq** [comment]
Is there any progress?

**Comment by dessalines** [comment]
Any movement on this, or does anyone know of an updated mention library?

**Comment by yasir-rafiq** [comment]
@dessalines use same method for any number of sign it will work.

**Comment by dessalines** [comment]
I don't think that would work, they need to point to different datasets obviously, `#` for tags, `@` for users

**Comment by yasir-rafiq** [comment]
can you mention your code where you stuck?

**Comment by dessalines** [comment]
I think I'm just going to have to fork and rewrite the datastructure since this project seems dead. Basically make the mention datastructure look like:

`mention: { 
  items: any;
  triggerChar: char;
  maxItems: number;
  labelKey: string;
}

And have `[mention] = [mention1, mention2....]`

**Comment by isabelatelles** [comment]
@dessalines Did you do it?

**Comment by isabelatelles** [comment]
@dessalines Oh that's nice of you! :) I'm currently working with angular 4. Do you think about publishing it for angular 4 as well?

**Comment by Cow-B** [comment]
@dessalines Hi, have you been successful to do anything with this? Thanks ! :)

**Comment by dessalines** [comment]
Yes I've made some progress in my branch, but I have some finishing touches to add to it.

**Comment by poonamOgale** [comment]
@dessalines hey is there any progress? I need to implement the same thing in angular 2.

**Comment by dessalines** [comment]
I haven't had time to look at this recently, but feel free to check out my branch at https://github.com/dessalines/angular-mentions/tree/devel

**Comment by poonamOgale** [comment]
Thanks for your reply! I am new to angular I m having issues with working
with the versions. Can you tell me if this works with angular version 6?

**Comment by poonamOgale** [comment]
@dessalines Thanks for the reply! Can you tell me if it works with angular 6?

**Comment by dmacfarlane** [comment]
This is supported in version 0.9.0.
