### ISSUE TITLE
Menu is at wrong position when input text is longer than the input field

### ISSUE THREAD

**Issue by binarious** [dmacfarlane/angular-mentions#3]
When pressing the trigger key without text overflow inside the input field, the menu positions as expected:
![1](https://cloud.githubusercontent.com/assets/200375/19305686/6818eba8-9072-11e6-9320-06d13127e469.png)

But when the text is longer than the input field, the menu is not positioned under the cursor anymore:
![2](https://cloud.githubusercontent.com/assets/200375/19305701/7b778236-9072-11e6-899d-68d1c36dbb2d.png)

**Comment by chaosLegacy** [comment]
same issue here any fix ??

**Comment by mcr85** [comment]
@dmacfarlane please check out my PR on that: https://github.com/dmacfarlane/angular-mentions/pull/88
