### ISSUE TITLE
Not working using Android (Chrome) browser

### ISSUE THREAD

**Issue by erikramalho** [dmacfarlane/angular-mentions#33]
This directive is not working when accessing from a Android(Chrome). I've tried both the live demo and a local project. None of them works. 

I've pressed the "@" but the dropdown list doesn't appear. 

Tried several android phones with different browsers. The only browser that worked was Firefox. On iOS, it works fine.

**Comment by erikramalho** [comment]
BTW the error is caused due the way android keyboard handle the keyup and keydown events. it always comes as 229 code and unidentified...

**Comment by amalshehu** [comment]
So any workarounds to tackle this issue?

**Comment by dmacfarlane** [comment]
I've committed a potential fix to the "android" branch. If someone can take a look and test the fix, that would be great.

**Comment by amalshehu** [comment]
Sure, will take a look into it.

**Comment by erikramalho** [comment]
Hey @dmacfarlane it **worked** in one of my devices (Motorola Moto G with Android 6.0)
I've built your branch and uploaded it in a host in case more folks decide to test.

[(http://angular-2-mentions-android.s3-website-us-west-2.amazonaws.com)]

**Comment by erikramalho** [comment]
Hey @dmacfarlane **UPDATE**
- it works in Android version 6.0

- **It's not working in android version greater then 6.0 (I've tested in two devices with Android version 6.1 and none of them worked**

**Comment by dmacfarlane** [comment]
Fixed with #94
