### ISSUE TITLE
How to get all mentions ? 

### ISSUE THREAD

**Issue by tuannla07** [dmacfarlane/angular-mentions#42]
For ex : I mention many people then i using Backspace to remove some of them, how i can get the final array of mentions ?

**Comment by dmacfarlane** [comment]
You would need to search the string to look for valid mentions.

**Comment by smkamranqadri** [comment]
Can you please share the code block for searching and getting all mentioned.

**Comment by dmacfarlane** [comment]
You could use a regular expression, something like: `\B@\w+`

**Comment by fzs1994** [comment]
If anyone is still looking, I've achieved using this:
```
this.mentionedUsers.forEach((element, i) => {
  if (!this.updatedDescription.includes(`[${element.label}]`)) {
    this.mentionedUsers.splice(i, 1);
  }
});
```
