### ISSUE TITLE
labelKey shouldn't be required if custom search is used

### ISSUE THREAD

**Issue by agarbund** [dmacfarlane/angular-mentions#44]
First of all, thanks for this library which allowed me to continue migrating my project from AngularJS to Angular by replacing Ment.io library.

I'm using newly provided `[mentionListTemplate]` option and doing custom complex search on my own.

Here is the code:
```
<textarea formControlName="content"
                  class="form-control"
                  [mention]="getSearchedItems()"
                  (searchTerm)="typedMention = $event"
                  [mentionListTemplate]="mentionItem"
                  [mentionConfig]="{mentionSelect: itemMentioned, disableSearch: true}"></textarea>
```

`getSearchedItems()` is a function which performs some complex search among array of objects using `typedMention` variable. `disableSearch` option is used to tell that I want to search by my own. With this config I don't have any results displayed even thou `getSearchedItems()` returns items. After investigation I found out, that items passed to `[mention]` are filtered by containing `labelKey` field (see: https://github.com/dmacfarlane/angular2-mentions/blob/master/src/mention/mention.directive.ts#L94 ).

As a workaround I added `labelKey: 'type'` to my `[mentionConfig]` object (all processed items have `type` field) but I think this shouldn't be required in this case.

@dmacfarlane I'd be happy to submit PR if you agree with my suggestion.

**Comment by dmacfarlane** [comment]
That's an interesting use case. Before the introduction of custom templates, I assumed there would always be a label that would need to be displayed. I'd be interested to see a PR on how you would disabled the filtering, sorting, and anywhere else `labelKey` is used. In the meantime, setting it to a common field seems like a reasonable work-around.

**Comment by agarbund** [comment]
K, I'll try to work on sth during the weekend.
