### ISSUE TITLE
HTML returned from `mentionSelect` function is being escaped

### ISSUE THREAD

**Issue by agarbund** [dmacfarlane/angular-mentions#45]
Hey @dmacfarlane it's me again :) I'm continuing rewrite of app to Angular 4 and encountered following issue:
I'm attaching `[mention]` to contenteditable div. A function which is formatting selected item returns HTML to style selected label nicely and disallow editing it:
```
onFieldSelect(item: Models.SourceField): string {
    return `<em data-id="${item.id}" contenteditable="false">${item.label}</em>`;
}
```

However, this HTML is being escaped when inserted to contenteditable element. Any idea how to bypass this?

**Comment by agarbund** [comment]
@dmacfarlane I've created PR resolving this issue: #50

**Comment by gurpreet2-kaur** [comment]
Can I apply CSS to element selected using mentionSelect

**Comment by agarbund** [comment]
@gurpreet2-kaur I don't see a reason why you couldn't

**Comment by silentsnooc** [comment]
@agarbund hi..

Is it formatting supposed to work like this:

```typescript
onMentionSelect(selection): string {
  return '<b>' + selection.label + '</b>';
}
```

Because the result in my `textarea` is just "\<b>Text\</b>" instead of "**Text**" .. any idea?

**Comment by agarbund** [comment]
@silentsnooc you can't have a formatted text in `textarea`. You need to use `[contenteditable]` attribute if you need formatting.

https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content

**Comment by agarbund** [comment]
If anyone reaches here in search for @mentions for Angular 2+ with support for HTML in `[contenteditable]`, I've created [ngx-tribute](https://github.com/ladderio/ngx-tribute), an Angular 2+ wrapper for @mentions library written in pure JS - [Tribute](https://github.com/zurb/tribute)

**Comment by silentsnooc** [comment]
@agarbund Could you provide an example? This is not working for me:

```xml
<div matInput placeholder="Beschreibung" style="resize: none;" 
          type="text" [mention]="mentions" [mentionConfig]="mentionConfig" contenteditable>              
</div>
```

**Comment by agarbund** [comment]
@silentsnooc can I see the issue somewhere? jsbin or sth like that

**Comment by silentsnooc** [comment]
@agarbund I created a stackblitz example: https://stackblitz.com/edit/angular-389kgl

**Comment by tanmayrajani** [comment]
> I am still getting `"<b>Text</b>"`.

I know this issue is quite old but this happens to me as well in a tinymce using iframe.. 

@dmacfarlane any plans on this? or am I missing something?

thanks!

**Comment by shtaimoortariq** [comment]
Yes I am also getting <b>Text</b> on latest version v1.1.3

**Comment by vamulya** [comment]
> @agarbund I created a stackblitz example: https://stackblitz.com/edit/angular-389kgl

hi @silentsnooc Is it working now?

**Comment by aeslinger0** [comment]
@tanmayrajani, my work-around for that is to return a blank string, wait a tick with setTimeout so the search term gets cleared out, then insert the html manually using tinymce's API.

**Comment by Manishpri** [comment]
> @agarbund Could you provide an example? This is not working for me:
> 
> ```
> <div [mention]="mentions" [mentionConfig]="mentionConfig" contenteditable 
>      style="padding-bottom: 24px;">              
> </div>
> ```
> 
> I am still getting " <b>Text</b>".

Still, I am facing the same issue,

**Comment by dmacfarlane** [comment]
Closing in favor of #170.

**Comment by kartik8393** [comment]
> @tanmayrajani, my work-around for that is to return a blank string, wait a tick with setTimeout so the search term gets cleared out, then insert the html manually using tinymce's API.

Can you please explain the exact solution or a stackblitz if possible.
