### ISSUE TITLE
 Customize text area input content

### ISSUE THREAD

**Issue by AshishTiwariMEAN** [dmacfarlane/angular-mentions#58]
Can you please update this plugin for customize text area input content, like if we want some hyperlink in the text.

So that we will implement in our website. It's important for us because Angular 1.x (https://github.com/angular-ui/ui-mention/) they give full customization. So that can you please update and let us know your valuable comments on the same.

**Comment by AshishTiwariMEAN** [comment]
Can you please suggest, is there any way to customize text area ?

**Comment by dmacfarlane** [comment]
As stated in #57 and #34:

> Custom formatting of text within input elements is not part of this package.

You will need to customize the content yourself after it has been selected.
