### ISSUE TITLE
The typeahead doesn't start appearing until the second search character is pressed in async mode (3rd including trigger char)

### ISSUE THREAD

**Issue by zman13** [dmacfarlane/angular-mentions#60]
I uncommented the async example in the demo code and can't seem to make it behave

```
<h3>Minimal Async</h3>
<input [mention]="httpItems | async" [mentionConfig]="{disableSearch:true}" (searchTerm)='search($event)' class="form-control" type="text">
```

The behavior I see is that the options window never opens on the first search character so if I type @a nothing will appear until the next character. Hitting the backspace sees will filter the names properly to those only containing "a" and if I hit backspace again it will often leave the list up without the trigger character being present as expressed in issue 59.
![no drop](https://user-images.githubusercontent.com/6117526/34127552-9a2a6e58-e40b-11e7-99fa-ffef7e156f46.PNG)

**Comment by erikramalho** [comment]
Same thing for me... any chance to solve this?? PLZ!

**Comment by kobvel** [comment]
Have you solved the issue somehow? @erikramalho @zman13

**Comment by kobvel** [comment]
I solved an issue by providing an option to disable search in the config
https://github.com/dmacfarlane/angular-mentions/pull/89
