### ISSUE TITLE
show mention list when press a button instead of type @

### ISSUE THREAD

**Issue by ghernagon** [dmacfarlane/angular-mentions#66]
I want to code something like Slack, in the text field, you have an @ button, when you press the @ button, do exactly what type @ does, anyone have advice to achieve that ?

Thx

**Comment by Cow-B** [comment]
I'm looking for the same functionnality. @ghernagon have you find a way ?

**Comment by dmacfarlane** [comment]
This is possible in version 1.1.1 as shown here:

https://stackblitz.com/edit/angular-mentions-button

**Comment by aeslinger0** [comment]
@dmacfarlane what about using `contentEditable`? Should that work as well? I tried this for TinyMCE, and it works if there's already content in the box, but it hangs if the box is empty.

    editor.ui.registry.addButton('mentionButton', {
      text: '@',
      tooltip: 'Mention someone',
      onAction: () => {
        const frame = <any>window.frames[editor.iframeElement.id];
        const contentEditable = frame.contentDocument.getElementById('tinymce');
        this.mention.startSearch('@', contentEditable);
      }
    });

Do I need to change how I'm doing it or are there known issues with contentEditable?

**Comment by jaymehtasa** [comment]
@aeslinger0 you were able to fix the issue when it's `contentEditable`, if possible please share the solution, I am also facing the same issue
