### ISSUE TITLE
Multiple mention list?

### ISSUE THREAD

**Issue by dessalines** [dmacfarlane/angular-mentions#71]
I need to do not just mentions with `@`, but also hashtags with `#`, is there any way to do that with this?

**Comment by dessalines** [comment]
`<input type="text" [mention]="[hashTagItems,userItems]" [mentionConfig]="{triggerChar:'[#,@]',maxItems:[10,10],labelKey:['name','tag']}">`

Doesn't work.

**Comment by dmacfarlane** [comment]
Duplicate of #22 and #25
