### ISSUE TITLE
Async search is not working

### ISSUE THREAD

**Issue by vijucalicut** [dmacfarlane/angular-mentions#76]
search($event) functionality not working for the given code.
<h3>Minimal Async</h3>
<input [mention]="httpItems | async" (searchTerm)='search($event)' class="form-control" type="text">

**Comment by dmacfarlane** [comment]
Duplicate of #60.

**Comment by vijucalicut** [comment]
Any fixes for this?

**Comment by dmacfarlane** [comment]
This may be fixed on the new config branch if you want to test it there.

**Comment by Fabf** [comment]
Can you say when it will be available on NPM?

**Comment by dmacfarlane** [comment]
I just published it for testing: `npm install angular-mentions@next`

**Comment by Fabf** [comment]
Great I Have tested the update and it seems to work now for async calls! 
Thank you!!
