### ISSUE TITLE
Issue with MS Edge when using triggerChar: '@'

### ISSUE THREAD

**Issue by felicksLindgren** [dmacfarlane/angular-mentions#77]
I stumbled upon this issue earlier this week where the dropdown doesn't trigger in MS Edge.

I debugged your mention.directive.ts and found out that MS Edge gives you a '2' instead of a '@' as event.key.

So I Implemented this if-statement `if(charPressed == 2 && event.altKey && event.ctrlKey){
            charPressed = '@';
        }` right after `let charPressed = this.keyCodeSpecified ? event.keyCode : event.key;` on line 134 inside your mention.directive.js file and it fixed the problem. 

You can probably find a better solution for this, but I wanted to submit this as a quick fix for the issue!

**Comment by dmacfarlane** [comment]
Unable to reproduce this on a MS Edge VM. The issue might already be fixed, so unless someone can confirm otherwise I will close this issue for now.

**Comment by casperkc** [comment]
I have the same issue with the latest version of Edge. I added the fix from @felicksLindgren and it does the trick. Would it be possible update the package with the fix?

**Comment by dmacfarlane** [comment]
I don't understand why `&& event.altKey && event.ctrlKey` is needed. Are these keys pressed when typing the `@` character?

**Comment by felicksLindgren** [comment]
Don’t really remember right now, but I’m pretty sure a checked which buttons were pressed when debugging the event and adjusted the condition accordingly.
