### ISSUE TITLE
How to disable the 'sort' function for mentionList?

### ISSUE THREAD

**Issue by vishnusbabu** [dmacfarlane/angular-mentions#79]
@dmacfarlane I need to disable the sort functionality from my mentionList array and display the array as it is declared.
Going  through the code i have seen sort is used in the ngOnIint() of directive.

**Comment by dmacfarlane** [comment]
If you're using `npm install angular-mentions@next` for the next version, the `disableSort` configuration option is documented here: 

https://github.com/dmacfarlane/angular-mentions/tree/config

**Comment by vishnusbabu** [comment]
Thanks a lot @dmacfarlane ..
Works fine :)

**Comment by dmacfarlane** [comment]
I'm unable to reproduce the issue. The mention list is closed after selecting an item with the mouse or pressing the enter key on Chrome and Firefox. Can you provide steps to reproduce, and/or a stackblitz example:

https://stackblitz.com/edit/angular-mentions

**Comment by vishnusbabu** [comment]
Hi @dmacfarlane, I have shared the stackblitz example which I tried and after selecting a mention list data the selection list isn't closing.

https://stackblitz.com/edit/angular-mentions-wmduvm

**Comment by dmacfarlane** [comment]
I removed the `mentionSelect` binding and added a missing return to the `itemMentioned` function:

https://stackblitz.com/edit/angular-mentions-tyuygy

**Comment by vishnusbabu** [comment]
Tried with it but internal functions aren't well working. I have used to functions to focus the string to a particular position.

**Comment by dmacfarlane** [comment]
Is the mention list in the updated example getting closed or is there another issue?

**Comment by vishnusbabu** [comment]
Yes the mention list is present but it consist of other functions to for finding the position of string and focusing the cursor position.

**Comment by vishnusbabu** [comment]
Depending to the above I just passed a parameter in mentionConfig it is working fine. 
 [mentionConfig]="{mentionSelect: itemMentioned, self: this, labelKey: 'tag', disableSort: true}"

'this' instance I have passed as a new parameter which is working fine for me.
