### ISSUE TITLE
disableSearch is not a valid MentionConfig option

### ISSUE THREAD

**Issue by trickeyone** [dmacfarlane/angular-mentions#83]
When typing the config object as a MentionConfig, I get the below error. It appears it was removed from the type declaration. I also don't see anywhere that it is being used in the latest version, 0.9.0. I only see `disableSearch` being set and checked on the actual MentionDirective itself. This is likely related to those who have been having issues with async searches.

```
TS2322: Type '{ triggerChar: string; labelKey: string; disableSort: true; disableSearch: boolean; }' is not assignable to type 'MentionConfig'.
  Object literal may only specify known properties, and 'disableSearch' does not exist in type 'MentionConfig'.
```

**Comment by trickeyone** [comment]
Thanks for the quick response @dmacfarlane ! If I'm reading the documentation correctly, isn't disabling search needed if you are wanting to do an sync search? i.e. querying an API for mentions? I see a few issues logged mentioning issues with async searching. Am I not reading things correctly?

**Comment by dmacfarlane** [comment]
It depends on requirements. If you want to filter (search) the results from the API using the local "startsWith" function then disabling search isn't needed. However, if you want to display all results from the API (including those that don't match the local filter) then disableSearch would be needed.

**Comment by trickeyone** [comment]
Well, no. Especially when dealing with things like mentions, you typically want to query an API. Most mention-setups I've dealt with tend to be API-driven, not static arrays. But, it's your project. I just know that this is a major limitation that makes the component unusable for us.

**Comment by dmacfarlane** [comment]
The disableSearch option is not required to enable async search. Take a look at the async example.
