### ISSUE TITLE
No denounce? 

### ISSUE THREAD

**Issue by seanlawrenz** [dmacfarlane/angular-mentions#84]
This should really have a debounce option.

**Comment by dmacfarlane** [comment]
I don't think it needs to be part of this component. You are fee to debounce the data-loading as shown in the async example.

**Comment by seanlawrenz** [comment]
This is a component that actions on keyboard events. People type at different speeds, and no production app will have a list of users pre-loaded into a component. Every use of a user mention requires some API call. That should be handed with a denouncer to cut calls or at the very least give a snappy feel for the user.

I'm able to bypass this problem, but it seemed like an unnecessary action.
