### ISSUE TITLE
At mention will work conditionally

### ISSUE THREAD

**Issue by mdshohelrana** [dmacfarlane/angular-mentions#91]
If my condition is fulfilled then "mention" will work otherwise won't work. Suppose I have a text area where I have configured mention list but according to our business condition mention will work conditionally otherwise not. 

If you have any configuration please help me. Waiting for your response.

**Comment by dmacfarlane** [comment]
There are some options here that might work: https://stackoverflow.com/q/44597077

**Comment by mdshohelrana** [comment]
I think this is the better way like this 
`[attr.mentionConfig]="condition ? '{mentionSelect: format, labelKey:'username', disableSearch: true}' : false"`

Rather than putting two html element. Could you add this type of condition 
`[attr.mentionConfig]="condition ? '{mentionSelect: format, labelKey:'username', disableSearch: true}' : false"` to your mention plugin.

Thanks in Advance.

**Comment by dmacfarlane** [comment]
Passing an empty config object should also work, for example:

`
[mentionConfig]="condition ? {mentionSelect: format, labelKey:'username', disableSearch: true} : {}"
`

Note that the configuration objects are not enclosed in quotes.

**Comment by mdshohelrana** [comment]
@dmacfarlane Great now it is working.
