### ISSUE TITLE
Request change updateConfig from private to public

### ISSUE THREAD

**Issue by vasyliv** [dmacfarlane/angular-mentions#93]
Thanks for your helpful library. Could you change access modifier of ``updateConfig`` in ``MentionDirective`` from **private** to **public**, I use this as a part of my project in a generic directive so I do all updates manually and simple updating doesn't work
```
this.mention.mention = x;
this.mention.updateSearchList();
```
so I need to do next
```
this.mention.mention = x;
this.mention['updateConfig']();
this.mention.updateSearchList();
```
and it works but lint has some errors to this line ``this.mention['updateConfig']();``

**Comment by dmacfarlane** [comment]
Done. This will be included in the next release.

**Comment by vasyliv** [comment]
thanks a lot.

**Comment by steve-heine** [comment]
can you share how you define this.mention?

**Comment by michael-vasyliv** [comment]
@steve-heine try this
```
@ContentChild(MentionDirective, { static: true }) mention: MentionDirective;
```

**Comment by steve-heine** [comment]
@michael-vasyliv  that was quick. Thanks!
