### ISSUE TITLE
Mention list overflowing window when cursor is at the edge of the screen

### ISSUE THREAD

**Issue by dtychshenko** [dmacfarlane/angular-mentions#95]
First of all, thank you for this library, it's awesome!

Not sure if this would be a bug or an enhancement request, but we have a textarea element where we use angular-mentions that happens to be located on the right edge of the window.

If a user types some text long enough that makes the cursor to be on the right edge of the textbox (and subsequently on the right edge of the window) and then presses "@" for the mentions, then most of the mentions list renders outside of the window making it unusable.

Here is a simple case to reproduce: https://stackblitz.com/edit/angular-svdoim

**Expected**: If the mentions list is going to overflow the window size on the right, I believe it should popup to the left of the cursor instead.

**Comment by dmacfarlane** [comment]
Let's just say it's a edge case... if any part of the list is outside the window then it needs to be re-positioned into the current window. For example:

```
if ( listX + listWidth > pageWidth ) {
  listX = pageWidth - listWidth;
}
```

Similar logic would need to be applied for the vertical position as well.

**Comment by dmacfarlane** [comment]
Fixed in the latest release.

**Comment by AsifKhurshid101** [comment]
I have used mention list in textarea.. I have fix this issue like this while open mention list as dropdown

opened(update?) {
const Parentbox_id = update ? 'Comment_Parent_' + update : 'text_area_parent';

    setTimeout(() => {
        var list = document.getElementById(Parentbox_id).querySelector(`mention-list[class="dropup"]`) as HTMLElement;

        if (!list) {
            list = document.getElementById(Parentbox_id).querySelector(`mention-list[class="null"]`);
        }

        let selObj = this.getWindowSelection(undefined);
        var selRange = selObj.getRangeAt(0);
        var anchorNode = selObj.anchorNode;
        var parentNode = anchorNode.parentNode !== null ? anchorNode.parentNode : selRange.commonAncestorContainer.parentNode;

        var offsetHeight = parentNode.offsetHeight; //19 fpr <p> tag
        var offsetTop = parentNode.offsetTop; //distance from top

        var top = update ? 27 : 31;

        if (parentNode.previousElementSibling) {
            top = offsetTop + (update ? 15 : 17);
            top = update ? top : top > 56 ? 56 : top;
        }

        if (list){
            //console.log("margin left", list.style.left);
            var getMarginLeft = list.style.left;
            var getActualValue = getMarginLeft.replace("px", "");
            var checkIfEdgeOut = Number(getActualValue);
            if(checkIfEdgeOut > 0)
            {
                list.style.cssText = `display:block !important;z-index:9999999999; position:absolute; left:${list.style.left}; top:${top}px`;
            }
            else {
                var str = "9.5px";
                list.style.cssText = `display:block !important; position:absolute; left:${str}; top:${top}px`;
                setTimeout(() => { list.style.cssText = `z-index:9999999999;`; }, 3000);
            }
        }

    }, 0);
}
