### ISSUE TITLE
Can't access a trigger char in searchTerm event

### ISSUE THREAD

**Issue by maximka777** [dmacfarlane/angular-mentions#97]
Hello!

It would be nice to get `triggerChar` which `searchTerm` event was triggered with since for different `triggerChar`s we can use different handlers.

Sorry if it's already implemented, but I didn't find.

**Comment by dmacfarlane** [comment]
It's not currently implemented, but it seems like a valid request. We'd need change the event to emit an object instead of a string.

**Comment by maximka777** [comment]
I think I could make this changes and open PR, if you are not opposed?

**Comment by dmacfarlane** [comment]
It needs to backwards compatible, so it may be better to create a different event and return the selected mention object in addition to the trigger char.

**Comment by dmacfarlane** [comment]
The `returnTrigger` option can now be used to include the trigger char in the searchTerm event.
